### PR TITLE
chore(ci) build nginx with stream_realip_module

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Adds `--with-stream_realip_module` to OpenResty `configure` flags.

See also:

- https://github.com/Kong/kong/pull/4163
- https://github.com/Kong/homebrew-kong/pull/86

### CODE REVIEW

**Review by thibaultcha — APPROVED** [review]
Ditto about `chore(ci)` scope for commit message.

**Comment by thibaultcha** [comment]
CI seems to fail though?

**Comment by thibaultcha** [comment]
This commit should be split in two. I seem to sense that most of the diff here was about bringing this repo's CI up-to-date with that of today's Kong/kong CI.

**Comment by bungle** [comment]
@thibaultcha it is now split in two. The `readme.md` change that adds right `patching ...` lines, I left to first commit (even if it is a bit unrelated to it).

**Review by hishamhm — APPROVED** [review]

**Pull request merged**
