### PR TITLE
fix(patches) remove service mesh patches from http subsystem for 1.15…

### PR DESCRIPTION
**Pull request by dndx**
….8.2

### CODE REVIEW

**Comment by bungle** [comment]
Can you also make it so that numbering is logical still?

**OK:**
```
LuaJIT-2.1-20190507_01-fix-tab-rechaining.patch
LuaJIT-2.1-20190507_02-fix-arm-arithmetic-condition-codes.patch
LuaJIT-2.1-20190507_03-dyn-lightuserdata-map.patch
```

**CHANGE:**
```
nginx-1.15.8-upstream_client_certificate.patch
nginx-1.15.8_01-stream-tls.patch
nginx-1.15.8_02-listen-transparent.patch
nginx-1.15.8_05-remove-server-tokens-from-special-responses-output.patch
```
**TO:**
```
nginx-1.15.8_01-upstream_client_certificate.patch
nginx-1.15.8_02-stream-tls.patch
nginx-1.15.8_03-listen-transparent.patch
nginx-1.15.8_04-remove-server-tokens-from-special-responses-output.patch
```

**DO WE NEED THESE:**
```
ngx_stream_lua-0.0.7_01-ssl-ctx.patch
ngx_stream_lua-0.0.7_04-starttls.patch
nginx-1.15.8_03-listen-transparent.patch
```

**Comment by dndx** [comment]
@bungle thanks for the review. The updated version has been tested with: https://travis-ci.org/Kong/kong/builds/608204383 and seems to be all passing.

**Review by kikito — APPROVED** [review]

**Comment by subnetmarco** [comment]
For anybody wondering about this PR, the Service Mesh capabilities have been released into Kuma (https://kuma.io). This will allow both Kong and Kuma to iterate on their own respective use-cases independently in a better way (and without cluttering the codebase). Kong and Kuma can talk together, so that APIM capabilities can still be provided on top of a Kuma mesh.

**Comment by kikito** [comment]
Closing this in favor of https://github.com/Kong/kong-build-tools/pull/165

**Pull request closed without merging**
