### PR TITLE
Dynamic lightuserdata mapping

### PR DESCRIPTION
**Pull request by javierguerragiraldez**
To allow architectures with VA larger than 47 bits, splits the space in 8 sections, each of 2^LJ_LUV_SECT_SHIFT bytes (2^45 on ARM64 (32TiB), VA is 48 bits).  Since the lightuserdata value must have zeros on all bits above 47, only sections [0..3] are valid.  The table `luv_sect_map[]` must map any section used by the memory layout into a valid section.  It should also be a symetric mapping, so a repeat of the transformation returns the original value.

The `luv_init_map()` function uses a sample of different types of pointers to determine with sections are actually used, and constructs the required table.

### CODE REVIEW

**Comment by james-callahan** [comment]
Also needed for `lua_cpcall`?

**Comment by javierguerragiraldez** [comment]
> Also needed for `lua_cpcall`?

or in `lightudV()`/`setlightudV()` ?  better to revisit the whole discussion in the previous PR

**Comment by james-callahan** [comment]
> revisit the whole discussion in the previous PR

Are you referring to https://github.com/Kong/openresty-patches/pull/47#issuecomment-513970988 ?

**Comment by javierguerragiraldez** [comment]
done, it's now on the lower level macros, so no need to grep where it should be added

**Comment by hishamhm** [comment]
Update: I just tested d330114 on an ARM64 box; it failed with `bad lightuserdata pointer`. Note it was not failing all the time: LuaRocks ran and installed `kong` successfully — so that means the patch _did_ apply (we would have seen failures much earlier otherwise). 

So I tried again with the previous version, f5e495d, and this is currently running the Kong test suite successfully.

**Comment by javierguerragiraldez** [comment]
darn.  i guess there's still some codepath that doesn't pass through the mapping.  or worse, passes an even number of times.   i have to get more familiar with the kong testsuite.

**Review by hutchic — APPROVED** [review]

**Comment by MartB** [comment]
This does not seem to fix the issue with knot-resolvers use of lua_pushlightuserdata (https://gitlab.labs.nic.cz/knot/knot-resolver/issues/216), it calls abort while trying to create a new state.

(I applied the patch to your exact sources and tried to use them on archlinux arm)

Backtrace:
```
#0  0x0000ffffbf0f1854 in raise () from /usr/lib/libc.so.6
#1  0x0000ffffbf0df2a8 in abort () from /usr/lib/libc.so.6
#2  0x0000ffffbf5210dc in ?? () from /usr/lib/libluajit-5.1.so.2
#3  0x0000ffffbf555d80 in lua_newstate () from /usr/lib/libluajit-5.1.so.2
#4  0x0000ffffbf56e808 in luaL_newstate () from /usr/lib/libluajit-5.1.so.2
-----
#5  0x0000aaaaaaaba834 in init_state (engine=0xaaaaaaae92e8 <engine>) at ../daemon/engine.c:582
#6  engine_init (engine=0xaaaaaaae92e8 <engine>, pool=0xfffffffff758) at ../daemon/engine.c:582
#7  0x0000aaaaaaab2cd8 in main (argc=<optimized out>, argv=<optimized out>) at ../daemon/main.c:762
```

im trying to figure out where exactly its failing atm.

Platform is aarch64 with VAbits = 48
`Linux 5.3.4-1-ARCH #1 SMP Mon Oct 7 00:09:02 UTC 2019 aarch64 GNU/Linux`

**Comment by javierguerragiraldez** [comment]
Hi @MartB, it seems that it can't find an appropriate map for your case.  Can you add a simple loop to print the contents of `luv_sect_map[]` at the entry of `luvmap_fold()`?

**Comment by MartB** [comment]
@javierguerragiraldez i collected the infos you wanted:

```
luv_sect_map[0] := 0
luv_sect_map[1] := 1
luv_sect_map[2] := 255
luv_sect_map[3] := 3
luv_sect_map[4] := 255
luv_sect_map[5] := 128
luv_sect_map[6] := 255
luv_sect_map[7] := 128
Aborted (core dumped)
```

after it completes the for loops  (before the last one with abort) it ends up with:
```
luv_sect_map[0] := 0
luv_sect_map[1] := 1
luv_sect_map[2] := 5
luv_sect_map[3] := 3
luv_sect_map[4] := 255
luv_sect_map[5] := 2
luv_sect_map[6] := 255
luv_sect_map[7] := 128
```

**Comment by javierguerragiraldez** [comment]
hum, this is certainly unsolvable with the given assumptions.  in short, it means that it wants to be able to store pointers in sectors 0, 1, 3, 5 and 7.  so it tries to map sectors 5 and 7, but there's only one free sector on the low half (sector 2).

if you're in control of all your C modules, and none of them uses a "just mask out the 48th bit" macro, then you could remove the second set of calls to `luvmap_mark_need()`, those that apply the `luv_mask47()` macro.  that might free up one or two lower half segments and allow the map to succeed.

**Comment by MartB** [comment]
I will try masking that out and check if/whatever fails afterwards, if it does i will just recompile the kernel with vabits 47. This is really annoying haha.

Thanks for your help!

Edit: That actually "solved" the issue and knot is now running, its dirty but its good enough for me until i find the motivation to recompile that kernel.

**Comment by vcunat** [comment]
Eww, it's great you found a work-around for your case, but the whole lightuserdata business in luajit is a rather painful story and I'm afraid it won't end anytime soon.

**Pull request merged**
