### PR TITLE
fix(transparent) include linux/in6.h before netinet/in.h

### PR DESCRIPTION
**Pull request by james-callahan**
Sending PR to get a travis run.

### CODE REVIEW

**Comment by thibaultcha** [comment]
Dup of #29 (also slightly broken)

**Comment by james-callahan** [comment]
> Dup of #29 (also slightly broken)

This is a PR against #29.

**Comment by james-callahan** [comment]
Was trying to simplify things, but I didn't realise the nginx feature checks aren't available until after the current `#include` section. Closing as your PR is fine.

**Comment by thibaultcha** [comment]
Ah my bad, it’s not obvious on mobile which branch a PR is opened against.

**Pull request closed without merging**
